# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_apply_cigar <- function(cigar, query, gap) {
    .Call(`_epialleleR_rcpp_apply_cigar`, cigar, query, gap)
}

rcpp_char_to_context <- function(ctx) {
    .Call(`_epialleleR_rcpp_char_to_context`, ctx)
}

rcpp_cx_report <- function(rname, strand, start, xm, pass, ctx) {
    .Call(`_epialleleR_rcpp_cx_report`, rname, strand, start, xm, pass, ctx)
}

rcpp_get_base_freqs <- function(read_rname, read_strand, read_start, read_end, read_seq, pass, vcf_chr, vcf_pos) {
    .Call(`_epialleleR_rcpp_get_base_freqs`, read_rname, read_strand, read_start, read_end, read_seq, pass, vcf_chr, vcf_pos)
}

rcpp_get_xm_beta <- function(xm, ctx_meth, ctx_unmeth) {
    .Call(`_epialleleR_rcpp_get_xm_beta`, xm, ctx_meth, ctx_unmeth)
}

rcpp_match_amplicon <- function(read_chr, read_start, read_end, ampl_chr, ampl_start, ampl_end, tolerance) {
    .Call(`_epialleleR_rcpp_match_amplicon`, read_chr, read_start, read_end, ampl_chr, ampl_start, ampl_end, tolerance)
}

rcpp_match_capture <- function(read_chr, read_start, read_end, capt_chr, capt_start, capt_end, min_overlap) {
    .Call(`_epialleleR_rcpp_match_capture`, read_chr, read_start, read_end, capt_chr, capt_start, capt_end, min_overlap)
}

rcpp_merge_ends <- function(read1_pos, read1_seq, read2_pos, read2_seq, isize, gap) {
    .Call(`_epialleleR_rcpp_merge_ends`, read1_pos, read1_seq, read2_pos, read2_seq, isize, gap)
}

rcpp_read_bam <- function(fn) {
    .Call(`_epialleleR_rcpp_read_bam`, fn)
}

rcpp_threshold_reads <- function(xm, ctx_meth, ctx_unmeth, ooctx_meth, ooctx_unmeth, min_n_ctx, min_ctx_meth_frac, max_ooctx_meth_frac) {
    .Call(`_epialleleR_rcpp_threshold_reads`, xm, ctx_meth, ctx_unmeth, ooctx_meth, ooctx_unmeth, min_n_ctx, min_ctx_meth_frac, max_ooctx_meth_frac)
}

