# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_char_to_context <- function(ctx) {
    .Call(`_epialleleR_rcpp_char_to_context`, ctx)
}

rcpp_cx_report <- function(df, pass, ctx) {
    .Call(`_epialleleR_rcpp_cx_report`, df, pass, ctx)
}

rcpp_fep <- function(df, colnames) {
    .Call(`_epialleleR_rcpp_fep`, df, colnames)
}

rcpp_get_base_freqs <- function(bam, pass, vcf) {
    .Call(`_epialleleR_rcpp_get_base_freqs`, bam, pass, vcf)
}

rcpp_get_xm_beta <- function(bam, ctx_meth, ctx_unmeth) {
    .Call(`_epialleleR_rcpp_get_xm_beta`, bam, ctx_meth, ctx_unmeth)
}

rcpp_match_amplicon <- function(bam, bed, tolerance) {
    .Call(`_epialleleR_rcpp_match_amplicon`, bam, bed, tolerance)
}

rcpp_match_capture <- function(bam, bed, min_overlap) {
    .Call(`_epialleleR_rcpp_match_capture`, bam, bed, min_overlap)
}

rcpp_read_bam_paired <- function(fn, min_mapq, min_baseq, skip_duplicates, nthreads) {
    .Call(`_epialleleR_rcpp_read_bam_paired`, fn, min_mapq, min_baseq, skip_duplicates, nthreads)
}

rcpp_threshold_reads <- function(df, ctx_meth, ctx_unmeth, ooctx_meth, ooctx_unmeth, min_n_ctx, min_ctx_meth_frac, max_ooctx_meth_frac) {
    .Call(`_epialleleR_rcpp_threshold_reads`, df, ctx_meth, ctx_unmeth, ooctx_meth, ooctx_unmeth, min_n_ctx, min_ctx_meth_frac, max_ooctx_meth_frac)
}

